# Generated by Django 3.2.3 on 2021-06-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ecommerce',
            new_name='Pizza',
        ),
    ]
